server:
  port: 8896
spring:
  application:
    name: b2b-goods-consumer
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@server1:8500/eureka/
    instance:
      hostname: localhost
feign:
  hystrix:
    enabled: true
thymeleaf:
  cache: false
  prefix: classpath:/template/
  suffix: .html
  encoding: UTF-8

