server:
  port: 8750
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/b2bgoods?useSSL=false&serverTimezone=Asia/Shanghai&&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: b2b-goods-provider
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@server1:8500/eureka/
  instance:
    hostname: localhost
mybatis:
  mapper-locations: classpath:/mapper/*
logging:
  level:
    com.itheima: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

